SELECT ?subject ?predicate ?object WHERE { VALUES ?subject { <https://purl.dsmz.de/brenda/enzyme/329> <https://purl.dsmz.de/brenda/reference/33656> <https://purl.dsmz.de/brenda/reference/771327> <https://purl.dsmz.de/brenda/reaction/S/429165> } ?subject ?predicate ?object } ORDER BY ?subject ?predicate ?object LIMIT 2000