SELECT ?subject ?predicate ?object WHERE { VALUES ?subject { <https://purl.dsmz.de/brenda/organism/10576> <https://purl.dsmz.de/brenda/organism/10674> <https://purl.dsmz.de/brenda/organism/10675> <https://purl.dsmz.de/brenda/organism/1199> <https://purl.dsmz.de/brenda/organism/17634> <https://purl.dsmz.de/brenda/organism/17664> <https://purl.dsmz.de/brenda/organism/22891> <https://purl.dsmz.de/brenda/organism/26454> <https://purl.dsmz.de/brenda/organism/424> <https://purl.dsmz.de/brenda/organism/9042> <https://purl.dsmz.de/brenda/organism/9556> <https://purl.dsmz.de/brenda/organism/9770> } ?subject ?predicate ?object } ORDER BY ?subject ?predicate ?object LIMIT 1000
