PREFIX d3o: <https://purl.dsmz.de/schema/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?pathway ?label WHERE { ?pathway a d3o:Pathway ; rdfs:label ?label . FILTER(CONTAINS(LCASE(STR(?label)), "entner")) } LIMIT 20
