PREFIX d3o: <https://purl.dsmz.de/schema/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT DISTINCT ?reaction ?role ?roleType ?compound ?name ?inchi ?inchikey WHERE { <https://purl.dsmz.de/brenda/pathway/76> d3o:hasReaction ?reaction . VALUES ?roleType { d3o:Substrate d3o:Product } ?role a ?roleType ; d3o:partOf ?reaction ; d3o:refersToCompound ?compound . OPTIONAL { ?compound rdfs:label ?name } OPTIONAL { ?compound d3o:hasStructure ?structure . ?structure d3o:hasInChI ?inchi . OPTIONAL { ?structure d3o:hasInChIKey ?inchikey } } } ORDER BY ?reaction ?roleType ?compound LIMIT 1000
